[package]
name = "worker_manager_lib"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "0.1.80"
tokio = { version = "1.38.0", features = ["full"] }
thiserror = "1.0.61"
anyhow = "1.0.86"
